# 显示 Makefile 的帮助。单独放成脚本是为了把控制台编码切到 UTF-8 ——
# 本机控制台默认 GBK，直接 echo 中文会乱码。

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

$lines = @(
  '串口 / RTT 工具箱 —— 一键操作'
  ''
  '  make open          起静态服务 + 打开自测浏览器（一键盘真机调试）'
  '  make serve         只起静态服务（前台，端口 8899；Ctrl+C 停）'
  '  make serve-stop    停掉占用 8899 的进程'
  '  make browser       只打开带 CDP 的自测浏览器（端口 9333）'
  ''
  '  make test          纯逻辑自测（RTT 协议 / ELF / HEX / 工程生成对账 / 探针 HID 协议，不需要硬件）'
  '  make test-offline  语法体检 + 全部离线逻辑回归（不启动浏览器、不占探针）'
  '  make test-board-matrix  检查四块活动板卡的例程、脚本和 ELF 路径'
  '  make test-gen      只跑「工程生成」页与 Python 工具产物的逐字节对账'
  '  make test-hid      只跑探针自定义 HID（RTT→CDC 转发）协议自测'
  '  make test-ui       页面端到端（演示串口 + 假探针，不需要硬件）'
  '  make test-ui-layout  全部 12 页在 1600/1280 下的布局检查与截图（不需要硬件）'
  '  make test-gen-page 「工程生成」页真页面验收（需要 make open 起的浏览器）'
  '  make test-dbg      调试器页的逻辑层（寄存器位域 / FPB 断点编码 / 命令解析 / 符号表 + 假目标跑一遍调试动作）'
  '  make test-dbg-page 调试器页的真页面验收（CDP + 内置假目标，不需要硬件）'
  '  make test-dbg-hw   调试器页的真机冒烟（真探针 + 真目标板；需探针没被别的浏览器占着）'
  '  make test-dbg-stress 调试器 ARM 真机压力测试（H743 靶子；发布前总验收，可与 gdb 逐地址比对）'
  '  make test-dbg-riscv  调试器 RISC-V 真机压力测试（HPM6800EVK 靶子 · JTAG 通路；可与 gdb 逐地址比对）'
  '  make dbg-step-hw   调试器真机验收：停止 / 单步 / 断点时「PC ↔ 源码行 ↔ 高亮 ↔ 滚动」是否同步'
  '  make spi-partial-hw  屏「局部刷新」真机验收：线上字节逐字节对账（ARGS=--panel=st77916 换档）'
  '  make test-record    记录到文件的落盘语义（.crswap / 积压 / 落盘进度；OPFS 替身，不需硬件）'
  '  make test-hw       真机 WebUSB RTT 验收（探针 + 目标板）'
  '  make test-hss-rate BOARD=ze  HSS/JScope 高速实测：备份原 Flash、烧录 72 MHz 测试固件、打开真实网页测速（支持 cb）'
  '  make tcpecho       以太网 TCP 回显：PC 当客户端打板子的 lwIP tcpecho（TCP_HOST=ip）'
  '  make tcpecho-server    PC 当 TCP 服务端（回显对照；TCP_PORT=port）'
  '  make tcpecho-selftest  不开硬件，本地 127.0.0.1 自检'
  '                     例程：hpm_sdk samples/lwip/lwip_tcpecho，板子=服务端 192.168.100.10:5001'
  '                     ARGS="--count 5 --payload PING\n" 换条数/内容'
  '  make probe-diag    探针 HID 直驱诊断（绕开页面）：rc=-4 归因 / RTT 字节级完整性'
  '                     ARGS="--mode=disc --iters=40 --clk=60"；口径与实测见 docs/probe-rc4-and-rtt-loss.md'
  '  make flash-timing  烧录耗时体检（真机：慢在哪一步、是不是探针的锅；ARGS=--clamp 模拟后台节流）'
  '  make hw-campaign   真机场景基准 · STM32F103ZE（烧录 / RTT Viewer / RTT 转发 / J-Scope，全跑一遍并判决）'
  '  make hw-campaign-f103cb  真机场景基准 · STM32F103CB（使用 CB 容量固件）'
  '  make hw-campaign-f103ze  真机场景基准 · STM32F103ZE（使用 ZE 容量固件）'
  '  make hw-campaign-h743     真机场景基准 · STM32H743（AXI SRAM 固件）'
  '  make hw-campaign-hpm  真机场景基准 · HPM6800EVK（RISC-V/JTAG，含 RTT Viewer 的 RISC-V 通路）'
  '                     ARGS=--record 只记录并给出 spec 建议；ARGS="--cycles=1 --alt=1" 冒烟'
  '  make campaign-summary  把基准结果打成小结表（跑完会自动打；也可指定历史 JSON，不碰硬件）'
  '  make test-bridge   桥端到端（OpenOCD + 探针 + 目标板）'
  '  make test-all      上面全跑一遍'
  '  make build-all-examples    增量构建四块活动板卡的全部例程'
  '  make rebuild-all-examples  先清旧 build/build-*，再全量重建（推荐发布前）'
  '  make clean-firmware        只清靶子固件生成目录（根 fw.elf 保留）'
  ''
  '  make bridge        起本地桥（OpenOCD 后端，默认目标 stm32f103）'
  '  make bridge-stop   停掉本地桥与 OpenOCD'
  ''
  '  make fw-build      编译 STM32F103 测试固件'
  '  make fw-flash      用 OpenOCD 烧测试固件'
  '  make fw-restore    = fw-build + fw-flash（板子被烧花了就用它救）'
  ''
  '  make fw-h7-build   编译 STM32H7B0 RTT 吞吐测试固件（HSE→PLL1 280MHz，HAL/SDK 版）'
  '  make fw-h7-flash   用 OpenOCD 烧 H7B0（首选还是网页里的零安装 WebUSB 烧录）'
  ''
  '  make algo-check    校验 algos.js 里各芯片 flash 算法条目是否自洽（不碰硬件）'
  '  make flash-plan    用纯计算演练一遍烧录计划（擦除/分块/补齐/范围，不碰硬件）'
  ''
  '  make la-info       逻辑分析仪状态（需要 KingstVIS 正在运行）'
  '  make la-capture    抓一段 SWD 波形到 tmp/la-now.csv'
  ''
  '  make git-status    git 状态 + 最近 5 条提交'
  '  make git-log       最近 15 条提交'
  '  make check         语法体检（node --check 各模块）'
  '  make clean         清临时采集文件 + 靶子固件生成目录（源码和根 fw.elf 保留）'
)
$lines | ForEach-Object { Write-Host $_ }

