/** Real F103CB SWO acceptance. Full original Flash is backed up twice and always restored.
 * Requires PB3 SWO wired to the probe VCOM RX and matching WebUSB/Web Serial grants. */
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {spawnSync} from 'node:child_process';import {resolve} from 'node:path';import {createHash} from 'node:crypto';
import {stageOracle} from './swo-stage-oracle.mjs';
import {Cdp,sleep} from './cdp-lib.mjs';import {packRecording} from '../../app/swo/recording.js';import {analyzeTrace} from '../../app/swo/analyze.js';
const out=process.env.SWO_OUT||'tmp/swo-hw',fixture='tools/target-firmware/stm32f103cb_swo/fw.elf',app=process.env.APP||'http://127.0.0.1:8911/index.html';
const c=new Cdp(process.env.CDP||'http://127.0.0.1:9345',30000),ocd=process.env.OPENOCD||'E:/Share/env-windows/xpack-openocd-0.12.0-6/bin/openocd.exe',scripts=process.env.OPENOCD_SCRIPTS||'E:/Share/env-windows/xpack-openocd-0.12.0-6/openocd/scripts',arm=process.env.ARM_BIN||'E:/Share/env-windows/tools/gnu_gcc/arm_gcc/mingw/bin/';
mkdirSync(out,{recursive:true});const report={board:'f103cb',app,fixture,rows:[],startedAt:new Date().toISOString()},sha=b=>createHash('sha256').update(b).digest('hex');let original,demcr,changed=false,restoreBytes;
const save=()=>writeFileSync(out+'/results.json',JSON.stringify(report,null,2));
const tcl=p=>{const q=resolve(p).replaceAll('\\','/');assert.ok(!/[{}\r\n]/.test(q));return '{'+q+'}'};
function command(t,label){const p=spawnSync(ocd,['-s',scripts,'-f','interface/cmsis-dap.cfg','-c','cmsis-dap backend usb_bulk','-f','target/stm32f1x.cfg','-c','adapter speed 1000','-c','gdb port disabled','-c','tcl port disabled','-c','telnet port disabled','-c',t],{encoding:'utf8',windowsHide:true,timeout:45000,maxBuffer:3e6});const text=(p.stdout||'')+(p.stderr||'');writeFileSync(out+'/'+label+'.log',text);assert.equal(p.status,0,label+': '+(p.error?.message||text));return text;}
const nm=spawnSync(arm+'arm-none-eabi-nm.exe',[fixture],{encoding:'utf8',windowsHide:true});assert.equal(nm.status,0);const syms=Object.fromEntries(nm.stdout.trim().split(/\r?\n/).filter(x=>x.trim().split(/\s+/).length===3).map(x=>{const [a,,n]=x.trim().split(/\s+/);return [n,parseInt(a,16)]}));
async function release(){await c.eval(`const t=__tools;if(t.swo.capture.active)await t.swo.capture.stop();if(t.dbg.session.connected)await t.dbg.disconnect();if(t.session.isOpen)await t.session.close();t.swo.pause();`);}
function oracle(model){const pcs=[...new Set(model.pcSamples.map(e=>e.pc))];const p=spawnSync(arm+'arm-none-eabi-addr2line.exe',['-f','-e',fixture],{input:pcs.map(x=>x.toString(16)).join('\n')+'\n',encoding:'utf8',windowsHide:true,maxBuffer:5e6});assert.equal(p.status,0);const rows=p.stdout.trim().split(/\r?\n/);let checked=0;const wrong=[];pcs.forEach((pc,i)=>{const fn=rows[2*i],match=/(.*):(\d+)(?:\s|$)/.exec(rows[2*i+1]||''),e=model.pcSamples.find(x=>x.pc===pc);if(!match||!Number(match[2])||!e.location)return;checked++;const base=s=>s.replaceAll('\\','/').split('/').pop();if(fn!==e.fn||base(match[1])!==base(e.location.file)||Number(match[2])!==e.location.line)wrong.push({pc,oracle:{fn,file:match[1],line:Number(match[2])},web:{fn:e.fn,location:e.location}});});assert.deepEqual(wrong,[],'GNU addr2line function/file/line agreement');assert.ok(checked>20);return {uniquePcs:pcs.length,checked,wrong};}
try{
 await c.connect();await c.send('Page.bringToFront');await c.send('Page.navigate',{url:app+'?swo-hw='+Date.now()+'#swo'});await sleep(700);await release();
 const bin=spawnSync(arm+'arm-none-eabi-objcopy.exe',['-O','binary',fixture,out+'/fixture.bin'],{encoding:'utf8',windowsHide:true});assert.equal(bin.status,0);restoreBytes=Math.ceil(readFileSync(out+'/fixture.bin').length/1024)*1024;
 const backup=command('init; halt; flash probe 0; echo "ORIGINAL_DEMCR [read_memory 0xe000edfc 32 1]"; dump_image '+tcl(out+'/original-flash.bin')+' 0x08000000 131072; dump_image '+tcl(out+'/original-confirm.bin')+' 0x08000000 131072; resume; shutdown','backup');assert.match(backup,/device id = 0x[0-9a-f]*410\b/i);assert.match(backup,/flash size = 128 KiB/i);demcr=Number(/ORIGINAL_DEMCR\s+(0x[0-9a-f]+|\d+)/i.exec(backup)[1]);original=readFileSync(out+'/original-flash.bin');assert.equal(original.length,131072);assert.deepEqual(readFileSync(out+'/original-confirm.bin'),original);writeFileSync(out+'/restore-pages.bin',original.subarray(0,restoreBytes));report.originalSHA256=sha(original);report.originalDemcr=demcr;report.restoreBytes=restoreBytes;save();
 changed=true;command('init; program '+tcl(fixture)+' verify reset exit','flash');await sleep(300);
 const elf=readFileSync(fixture),sources=Object.fromEntries(['main.c','pipeline.c','startup.c','pipeline.h'].map(n=>[n,readFileSync('tools/target-firmware/stm32f103cb_swo/src/'+n,'utf8')]));
 await c.eval(`const v=__tools.swo;await v.loadElf(Uint8Array.from(atob(${JSON.stringify(elf.toString('base64'))}),c=>c.charCodeAt(0)).buffer,'f103cb_swo.elf');v.sources.indexFileList(Object.entries(${JSON.stringify(sources)}).map(([n,t])=>new File([t],n)));document.getElementById('sw-core').value=8;document.getElementById('sw-baud').value=1000000;`);
 for(const [i,cfg] of [{scenario:0,itm:false,period:4096,seconds:5},{scenario:1,itm:true,period:4096,seconds:5},{scenario:0,itm:true,period:1024,seconds:3},{scenario:0,itm:true,exceptions:true,period:4096,seconds:3},{scenario:1,itm:true,baud:4000000,period:256,seconds:3}].entries()){
   await release();command('init; mww 0x'+syms.g_scenario.toString(16)+' '+cfg.scenario+'; sleep 350; shutdown','scenario-'+i);
   await c.eval(`document.getElementById('sw-baud').value=${cfg.baud||1000000};document.getElementById('sw-period').value=${cfg.period};document.getElementById('sw-seconds').value=${cfg.seconds};document.getElementById('sw-itm').checked=${cfg.itm};document.getElementById('sw-exceptions').checked=${!!cfg.exceptions};await __tools.swo.start();`);
   for(let n=0;n<160;n++){if(await c.eval(`return !__tools.swo.capture.active&&!__tools.swo.analyzing&&!!__tools.swo.result;`))break;await sleep(100);}
   const web=await c.eval(`const v=__tools.swo;if(!v.result)throw Error(document.getElementById('sw-warning').textContent);let text='';const raw=v.recording.raw;for(let p=0;p<raw.length;p+=8192)text+=String.fromCharCode(...raw.subarray(p,p+8192));return {raw:btoa(text),metadata:v.recording.metadata,stats:v.result.stats,hotspots:v.result.hotspots,errors:__tools.errors,sourceTitle:document.getElementById('sw-source-title').textContent};`);
   const raw=Buffer.from(web.raw,'base64');delete web.raw;writeFileSync(out+'/capture-'+i+'.swopc',packRecording(raw,web.metadata));writeFileSync(out+'/capture-'+i+'.bin',raw);const model=analyzeTrace(raw,web.metadata,elf);const names=model.hotspots.map(x=>x.fn);
   const row={cfg,bytes:raw.length,...web,oracle:oracle(model),exceptions:model.events.filter(e=>e.kind==='exception').reduce((m,e)=>({...m,[e.exception]:(m[e.exception]||0)+1}),{}),stageOracle:stageOracle(model),markerCount:model.events.filter(e=>e.kind==='itm'&&e.port===1).length};report.rows.push(row);save();
   assert.equal(web.metadata.restored,true);assert.equal(web.metadata.transportGaps.length,0);assert.equal(web.stats.malformed,0);if(!cfg.exceptions)assert.equal(web.stats.overflow,0);else assert.ok(model.events.some(e=>e.kind==='gap'&&e.reason.includes('溢出')),'observed exception burst losses explicitly surfaced');assert.equal(web.stats.droppedEvents,0);assert.deepEqual(web.errors,[]);assert.ok(web.stats.analyzedSamples>cfg.seconds*web.metadata.plan.samplesHz*.6);assert.ok(web.stats.mapped/web.stats.analyzedSamples>.99);assert.ok(names.includes(cfg.scenario?'branch_leaf_b':'branch_leaf_a'));assert.ok(!names.includes(cfg.scenario?'branch_leaf_a':'branch_leaf_b'));assert.ok(!names.includes('never_path'));for(const name of ['crc_step','insertion_sort','encode_word','recursive_mix','verify_block'])assert.ok(names.includes(name),name+' sampled');if(cfg.exceptions)assert.ok(row.exceptions[15]>100);else assert.equal(web.stats.exceptions,0);
   if(cfg.itm){assert.ok(row.stageOracle.checked>1000);assert.equal(row.stageOracle.mismatchCount,0,'independent stage marker / observed PC agreement');const markers=model.events.filter(e=>e.kind==='itm'&&e.port===1&&((e.value>>>24)===0xa5));assert.ok(markers.length>20);const phases=new Set(markers.map(e=>e.value&255));assert.ok(phases.has(cfg.scenario?4:3));assert.ok(!phases.has(cfg.scenario?3:4));for(let j=1;j<markers.length;j++)assert.equal((markers[j].value>>>8)&65535,(((markers[j-1].value>>>8)&65535)+1)&65535,'stage marker sequence');row.phases=[...phases];}
   const sampled=model.pcSamples.find(e=>e.fn===(cfg.scenario?'branch_leaf_b':'branch_leaf_a'));await c.eval(`await __tools.swo.selectSample(${sampled.sample});`);writeFileSync(out+'/capture-'+i+'.png',Buffer.from((await c.send('Page.captureScreenshot',{format:'png'})).data,'base64'));
   console.log(JSON.stringify({case:i,...cfg,bytes:raw.length,pc:web.stats.analyzedSamples,functions:names.length,oracle:row.oracle.checked,markerCount:row.markerCount,stats:web.stats}));save();
 }
 report.passed=true;
}catch(e){report.error=e.stack;process.exitCode=1;console.error(e.stack);}
finally{
 try{await release();}catch(e){report.releaseError=e.stack;process.exitCode=1;}
 if(original&&changed){try{const log=command('init; reset halt; flash write_image erase '+tcl(out+'/restore-pages.bin')+' 0x08000000; verify_image '+tcl(out+'/restore-pages.bin')+' 0x08000000; dump_image '+tcl(out+'/restored-flash.bin')+' 0x08000000 131072; mww 0xe000edfc '+demcr+'; reset run; mww 0xe000edfc '+demcr+'; echo "RESTORED_DEMCR [read_memory 0xe000edfc 32 1]"; shutdown','restore');const restored=readFileSync(out+'/restored-flash.bin');assert.deepEqual(restored,original);assert.equal(Number(/RESTORED_DEMCR\s+(0x[0-9a-f]+|\d+)/i.exec(log)[1]),demcr);report.restore={passed:true,sha256:sha(restored),bytes:restored.length,pages:restoreBytes/1024,demcr};console.log('Original F103CB Flash fully restored and verified');}catch(e){report.restore={passed:false,error:e.stack};process.exitCode=1;console.error('RESTORE FAILED',e.stack);}}
 save();c.close();
}
